In [1]:
import pandas as pd

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("C:\\Users\\DANISH\\Documents\\convid-19_toy.csv")

In [4]:
print(data.head())

        fever  bodypain  age  runnynoise  diffBreath  infectionProb
0   99.740986         1   14           0           1              0
1  100.355980         1   85           1           1              0
2   98.438985         0   29           0           0              1
3   99.779852         0   83           0          -1              1
4   98.559619         0   31           1           0              0


In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2566 entries, 0 to 2565
Data columns (total 6 columns):
fever            2566 non-null float64
bodypain         2566 non-null int64
age              2566 non-null int64
runnynoise       2566 non-null int64
diffBreath       2566 non-null int64
infectionProb    2566 non-null int64
dtypes: float64(1), int64(5)
memory usage: 120.4 KB


In [6]:
data['fever'].value_counts()

101.350884    1
101.967637    1
98.505582     1
98.743480     1
98.461225     1
98.373392     1
101.090084    1
101.193083    1
100.282983    1
98.205861     1
99.804891     1
100.668571    1
101.902373    1
101.457228    1
99.159293     1
100.034963    1
100.837509    1
101.397370    1
101.585698    1
100.148454    1
98.813636     1
98.292101     1
100.008345    1
99.880151     1
100.851269    1
98.379313     1
99.929664     1
99.258263     1
100.326031    1
98.457799     1
             ..
98.980930     1
101.617171    1
99.830808     1
101.986458    1
101.004773    1
101.480707    1
98.920651     1
98.453356     1
99.889093     1
98.635989     1
99.422700     1
101.274862    1
99.846281     1
101.586784    1
98.492734     1
99.047680     1
101.590836    1
101.562661    1
101.457084    1
99.388901     1
101.615638    1
101.988787    1
100.805878    1
100.392946    1
99.686457     1
99.755111     1
98.691355     1
98.775513     1
99.638179     1
101.778773    1
Name: fever, Length: 256

In [7]:
data.describe()

fever     bodypain          age   runnynoise   diffBreath  \
count  2566.000000  2566.000000  2566.000000  2566.000000  2566.000000   
mean    100.001637     0.495713    49.800857     0.512081     0.002728   
std       1.138957     0.500079    29.456131     0.499951     0.813382   
min      98.001670     0.000000     1.000000     0.000000    -1.000000   
25%      99.040635     0.000000    24.000000     0.000000    -1.000000   
50%      99.986612     0.000000    49.000000     1.000000     0.000000   
75%     100.975778     1.000000    76.000000     1.000000     1.000000   
max     101.999801     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2566.000000  
mean        0.498051  
std         0.500094  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

## TRAIN TEST SPLIT

In [8]:
import numpy as np


In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [10]:
train,test = data_split(data,0.2)

In [11]:
train


fever  bodypain  age  runnynoise  diffBreath  infectionProb
2309   98.618168         0   64           1           1              0
361    99.598902         1   64           0          -1              1
1255   99.274113         1    1           1           1              1
1225   99.434060         0   53           1          -1              0
1933   98.007038         0   87           0           1              1
1351   99.407557         1   53           1           1              0
1505  100.376488         0   24           1          -1              1
2248   99.889093         0   94           0          -1              0
889    99.147799         0   16           0           1              0
767   101.491034         0    7           0          -1              0
240   101.541489         1   15           1          -1              1
1113   98.100547         1   40           1          -1              1
596    98.573160         1   11           1           1              1
2539  101.503412         1   47           0          -1              0
1226   98.026720         0   56           1           1              0
350    99.833218         0   97           1           0              1
2352   99.259426         1   68           1          -1              1
807    98.564861         1   51           0          -1              1
2030   98.049123         0   28           1           0              1
1702   98.450805         1   24           0          -1              0
834    98.215931         1   25           0           1              0
2512   98.556140         0   30           0           0              1
748   101.989855         0   97           1           1              1
890    98.769776         0    1           1          -1              0
2108  100.012331         1   51           0           0              1
602    98.600575         1   18           1           1              1
1925   98.920651         1   38           1           0              1
923   101.843164         1   63           1           1              1
1975   99.930352         1   23           0           0              1
2002   99.740945         1   73           1           0              1
...          ...       ...  ...         ...         ...            ...
1806   98.561213         1    5           0          -1              0
975   101.433775         1   52           1           1              1
2047  101.818987         1   41           0           0              1
1082   99.228749         0   46           1           1              0
474   100.752145         0   84           1           0              1
747   100.703875         1   72           1           1              1
2300  100.318618         0   89           1          -1              1
21    101.878761         1   92           1          -1              1
459    98.786779         1   18           0           1              0
1184  101.307805         0   81           0           1              0
2324  100.138117         0   95           0          -1              0
955   100.985538         1   11           1           1              0
1215   99.972858         1   43           1           0              0
2433  101.429748         1   84           1          -1              0
1515  100.567845         0   89           1           1              0
2391  101.958070         1   27           0           1              1
769   101.397803         1   36           1          -1              0
1685   99.253251         0   86           0          -1              1
130    98.977710         0   66           1          -1              1
2135  101.332989         0   70           1           1              0
1482   99.738055         0   26           1           1              1
330    99.128863         0   87           0          -1              1
1238  100.518714         0   39           0           1              1
466    99.948699         1   71           0          -1              1
2169  100.580953         1   13    

In [12]:
test

fever  bodypain  age  runnynoise  diffBreath  infectionProb
973   100.783946         0   58           0           0              1
2080  101.386503         1   77           1           1              0
1281   99.386765         0   35           0           0              1
952   101.170227         0   55           0           0              1
2530  101.905688         1   44           0           0              1
1669   98.196318         1   98           0           0              0
1902  101.383070         0   21           0          -1              0
178   101.417224         1   20           0           0              1
1420  101.209167         0   67           1           1              0
1926  100.929633         0   44           1           0              0
1124   98.301466         1   93           0          -1              0
643   101.783376         1   79           1           0              0
2098  100.708277         0   77           1           1              1
318   100.600216         0   35           1          -1              1
2508   99.238998         0   95           1           0              1
736    98.539495         0   39           1           0              1
1199   98.386014         1   80           1           0              1
1765  101.105143         1   41           0           0              1
1325  100.426250         0   33           0          -1              1
1616  101.382450         0   79           1           1              0
282   100.801140         0   13           0          -1              1
1407  101.274862         1   49           0          -1              1
2430  100.856715         0   82           1          -1              1
443    99.882073         1   36           1           0              0
1317   98.128700         0   89           0           0              0
1173   99.255721         1   35           1          -1              0
2035   98.965289         0   89           0           1              0
1106  101.147472         1   79           0           1              0
1472  100.936714         0   44           1          -1              1
2162   99.456833         0   37           0          -1              0
...          ...       ...  ...         ...         ...            ...
532   101.996241         0    2           0           0              1
1455   99.890304         0   54           0           0              1
166   101.462483         0   91           0           1              0
1268  100.292891         1   59           1          -1              0
867    98.408749         0   39           1           1              0
1017   98.943265         1   43           1           1              0
1048   99.222325         0   63           0           0              0
49     98.955450         1   23           1           1              0
67     99.296542         1   45           1           0              0
1110  101.693942         0    6           1          -1              1
2330   99.569550         1   21           1           0              1
565   100.623016         1   72           0           1              0
48     98.067959         0   88           1           0              0
1532  100.232879         0   13           1           0              0
2268  101.634838         1   20           1          -1              0
879   100.857238         0   18           0          -1              0
1414   99.934638         0   25           0          -1              1
124    99.063809         0   98           1           1              1
2297   98.611823         0   87           1          -1              0
1360  101.710811         0   57           1           0              1
471   100.986735         1   21           1           0              0
695   100.638203         1   16           1           1              1
926    99.134280         0   48           0           1              1
1047   99.040256         1   67           0           1              0
25    100.206290         0   83    

In [13]:
X_train = train[['fever','bodypain','age','runnynoise','diffBreath']]

In [14]:
X_train

fever  bodypain  age  runnynoise  diffBreath
2309   98.618168         0   64           1           1
361    99.598902         1   64           0          -1
1255   99.274113         1    1           1           1
1225   99.434060         0   53           1          -1
1933   98.007038         0   87           0           1
1351   99.407557         1   53           1           1
1505  100.376488         0   24           1          -1
2248   99.889093         0   94           0          -1
889    99.147799         0   16           0           1
767   101.491034         0    7           0          -1
240   101.541489         1   15           1          -1
1113   98.100547         1   40           1          -1
596    98.573160         1   11           1           1
2539  101.503412         1   47           0          -1
1226   98.026720         0   56           1           1
350    99.833218         0   97           1           0
2352   99.259426         1   68           1          -1
807    98.564861         1   51           0          -1
2030   98.049123         0   28           1           0
1702   98.450805         1   24           0          -1
834    98.215931         1   25           0           1
2512   98.556140         0   30           0           0
748   101.989855         0   97           1           1
890    98.769776         0    1           1          -1
2108  100.012331         1   51           0           0
602    98.600575         1   18           1           1
1925   98.920651         1   38           1           0
923   101.843164         1   63           1           1
1975   99.930352         1   23           0           0
2002   99.740945         1   73           1           0
...          ...       ...  ...         ...         ...
1806   98.561213         1    5           0          -1
975   101.433775         1   52           1           1
2047  101.818987         1   41           0           0
1082   99.228749         0   46           1           1
474   100.752145         0   84           1           0
747   100.703875         1   72           1           1
2300  100.318618         0   89           1          -1
21    101.878761         1   92           1          -1
459    98.786779         1   18           0           1
1184  101.307805         0   81           0           1
2324  100.138117         0   95           0          -1
955   100.985538         1   11           1           1
1215   99.972858         1   43           1           0
2433  101.429748         1   84           1          -1
1515  100.567845         0   89           1           1
2391  101.958070         1   27           0           1
769   101.397803         1   36           1          -1
1685   99.253251         0   86           0          -1
130    98.977710         0   66           1          -1
2135  101.332989         0   70           1           1
1482   99.738055         0   26           1           1
330    99.128863         0   87           0          -1
1238  100.518714         0   39           0           1
466    99.948699         1   71           0          -1
2169  100.580953         1   13           0           1
1638   99.255946         0   78           0           0
1095   99.773962         1   96           1           1
1130   98.684336         0    8           0           1
1294   99.541484         0   24           1          -1
860    98.729590         0    6           1           0

[2053 rows x 5 columns]

In [15]:
X_train.to_numpy()

array([[98.61816842,  0.        , 64.        ,  1.        ,  1.        ],
       [99.59890188,  1.        , 64.        ,  0.        , -1.        ],
       [99.27411254,  1.        ,  1.        ,  1.        ,  1.        ],
       ...,
       [98.68433556,  0.        ,  8.        ,  0.        ,  1.        ],
       [99.54148433,  0.        , 24.        ,  1.        , -1.        ],
       [98.72959006,  0.        ,  6.        ,  1.        ,  0.        ]])

In [16]:
X_test = test[['fever','bodypain','age','runnynoise','diffBreath']].to_numpy()

In [17]:
X_test

array([[100.7839457 ,   0.        ,  58.        ,   0.        ,
          0.        ],
       [101.386503  ,   1.        ,  77.        ,   1.        ,
          1.        ],
       [ 99.38676493,   0.        ,  35.        ,   0.        ,
          0.        ],
       ...,
       [ 99.67588631,   0.        ,  53.        ,   1.        ,
         -1.        ],
       [101.4208408 ,   1.        ,  94.        ,   0.        ,
         -1.        ],
       [ 98.68470523,   1.        ,  12.        ,   0.        ,
          1.        ]])

In [18]:
Y_train = train[['infectionProb']].to_numpy().reshape(2053, )

In [19]:
Y_train

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [20]:
Y_test = test[['infectionProb']].to_numpy().reshape(513, )

In [21]:
Y_test

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,

## MODEL CREATION 

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
clf = LogisticRegression()

In [24]:
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
input_features = [102, 1, 22, -1, 1]

In [26]:
input_features

[102, 1, 22, -1, 1]

In [27]:
infProb = clf.predict_proba([input_features])[0][1]

In [28]:
infProb

0.49783105238002606